/**
 * Playwright config for the v0.3.0 W3 visual regression CI gate.
 *
 * Two projects:
 *   * ``dom``  — DOM-snapshot byte-equality (CI-gating per ADR-001).
 *   * ``ssim`` — pixel SSIM (advisory; nightly only per ADR-001).
 *
 * The runner is invoked from ``scripts/visual_regression/run_dom_snapshots.sh``
 * (per-PR DOM smoke + Make target ``audit-2026-visual-regression-dom``)
 * and from ``scripts/visual_regression/run_ssim.sh`` (nightly SSIM
 * advisory + Make target ``audit-2026-visual-regression-ssim``).
 *
 * Determinism notes (ADR-001):
 *   * DOM bytes are deterministic across Chromium versions because the
 *     DOM tree is generated by React from form_spec.json + Step.tsx,
 *     both of which are deterministic outputs of the generator. Pixel
 *     bytes are NOT deterministic — font hinting / GPU compositing /
 *     antialiasing drift between Chromium minor versions.
 *   * The dev server is per-flavor: the generated frontends already
 *     emit per-bundle Vite + React 18 SPAs under
 *     ``examples/<example>/generated/frontend-admin/<package>/``. The
 *     "frontend" flavor (Step.tsx pages) requires a Vite harness that
 *     mounts each Step against an in-memory props stub — that harness
 *     lives at ``tests/visual_regression/harness/`` (not yet committed:
 *     follow-up PR that lands once ``pnpm install`` is unblocked).
 */
import { defineConfig, devices } from "@playwright/test";

const SHOULD_REQUIRE_BASELINES = process.env.UPDATE_BASELINES !== "1";

export default defineConfig({
	testDir: "./tests",
	timeout: 30_000,
	expect: {
		timeout: 5_000,
	},
	// Determinism over speed: 1 worker so failures stream cleanly.
	workers: process.env.CI ? 1 : undefined,
	fullyParallel: false,
	reporter: process.env.CI ? "github" : "list",
	forbidOnly: !!process.env.CI,
	retries: 0,
	use: {
		// We do not use baseURL — each test navigates by absolute URL via
		// the dev server fixture (see lib/dev_server.ts; lands alongside
		// the harness in the follow-up PR).
		trace: "off",
		video: "off",
		screenshot: "off",
	},
	projects: [
		{
			name: "dom",
			testMatch: /dom_snapshot\.spec\.ts/,
			use: {
				...devices["Desktop Chrome"],
			},
			metadata: {
				adr: "ADR-001",
				gate: "ci-blocking",
				artifact: "dom-bytes",
				cadence: "per-pr-smoke + nightly-full",
				requireBaselines: SHOULD_REQUIRE_BASELINES,
			},
		},
		{
			name: "ssim",
			testMatch: /pixel_ssim\.spec\.ts/,
			use: {
				...devices["Desktop Chrome"],
			},
			metadata: {
				adr: "ADR-001",
				gate: "advisory",
				artifact: "pixel-ssim",
				cadence: "nightly-only",
				ssimThreshold: 0.98,
				requireBaselines: SHOULD_REQUIRE_BASELINES,
			},
		},
	],
});
