"""Form specification model. Generated by the JTBD generator and rendered
by ``@flowforge/renderer``."""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field as PField

FieldKind = Literal[
	"text",
	"number",
	"money",
	"date",
	"datetime",
	"enum",
	"boolean",
	"party_ref",
	"document_ref",
	"email",
	"phone",
	"address",
	"textarea",
	"signature",
	"file",
	"lookup",
]


class FormFieldOption(BaseModel):
	model_config = ConfigDict(extra="forbid")

	v: str
	label: str | None = None


class Field(BaseModel):
	model_config = ConfigDict(extra="forbid")

	id: str
	kind: FieldKind
	label: str | None = None
	required: bool = False
	pii: bool = False
	default: Any = None
	options: list[FormFieldOption] = PField(default_factory=list)
	validation: dict[str, Any] = PField(default_factory=dict)
	source: dict[str, Any] | None = None


class FormLayoutSection(BaseModel):
	model_config = ConfigDict(extra="forbid")

	kind: Literal["section"] = "section"
	title: str | None = None
	field_ids: list[str]


class FormSpec(BaseModel):
	model_config = ConfigDict(extra="forbid")

	id: str
	version: str
	title: str
	fields: list[Field]
	layout: list[FormLayoutSection] = PField(default_factory=list)
