"""Tests for shared JTBD template rendering helpers."""

from __future__ import annotations

from pathlib import Path

from flowforge_cli.jtbd._render import _py_repr, _to_json, render


def test_to_json_sorts_keys_and_stringifies_unknown_values() -> None:
	assert _to_json({"b": Path("bundle.json"), "a": 1}, indent=0) == (
		'{\n"a": 1,\n"b": "bundle.json"\n}'
	)


def test_py_repr_returns_python_literal_representation() -> None:
	assert _py_repr({"role": "reviewer"}) == "{'role': 'reviewer'}"


def test_render_uses_shared_template_environment() -> None:
	body = render(
		"env.example.j2",
		project={
			"name": "Review Ops",
			"package": "review_ops",
			"tenancy": "single",
			"languages": ["en"],
			"currencies": ["USD"],
		},
	)

	assert "# Review Ops — generated by flowforge JTBD generator" in body
	assert "DATABASE_URL=sqlite+pysqlite:///review_ops.db" in body
