"""Per-JTBD router-level idempotency dedupe helper.

Emits ``backend/src/<pkg>/<jtbd>/idempotency.py`` — a SQLAlchemy-backed
helper used by the generated FastAPI router to enforce the
``Idempotency-Key`` header on ``POST /<jtbd>/events`` (v0.3.0 W2 /
item 6). The helper writes / reads the per-JTBD
``<table>_idempotency_keys`` table the chained ``db_migration``
generator emits.

Constants the helper exposes:

* ``IDEMPOTENCY_TABLE`` — string name of the per-JTBD table.
* ``IDEMPOTENCY_TTL_HOURS`` — int hours; bundle-overridable via
  ``project.idempotency.ttl_hours``; default 24h when not set.
* ``check_idempotency_key`` / ``record_idempotency_response`` —
  async callables the router uses on every event POST.

The router-side wrapper is generated by ``domain_router.py.j2``; the
service-side dedupe call lives in ``domain_service.py.j2``. This module
only exposes the *helpers*; the router/service templates wire them.
"""

from __future__ import annotations

from .._render import render
from ..normalize import NormalizedBundle, NormalizedJTBD
from .._types import GeneratedFile


# Bundle paths this generator reads — declared so the fixture-coverage
# audit can confirm at least one example exercises every input field.
CONSUMES: tuple[str, ...] = (
	"jtbds[].class_name",
	"jtbds[].id",
	"jtbds[].module_name",
	"jtbds[].table_name",
	"project.idempotency.ttl_hours",
	"project.package",
)


# Default replay window when the bundle does not opt into a custom TTL.
# Keep in sync with the ``IDEMPOTENCY_TTL_HOURS`` literal the template
# substitutes when ``project.idempotency_ttl_hours is None``.
DEFAULT_TTL_HOURS = 24


def generate(bundle: NormalizedBundle, jtbd: NormalizedJTBD) -> GeneratedFile:
	"""Emit the per-JTBD idempotency helper module."""

	ttl_hours = bundle.project.idempotency_ttl_hours
	if ttl_hours is None:
		ttl_hours = DEFAULT_TTL_HOURS

	content = render(
		"idempotency.py.j2",
		project=bundle.project,
		jtbd=jtbd,
		ttl_hours=ttl_hours,
	)
	return GeneratedFile(
		path=f"backend/src/{bundle.project.package}/{jtbd.module_name}/idempotency.py",
		content=content,
	)
